apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: honeypot-rs-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: honeypot-rs-runtime
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: honeypot-rs
  data:
    - secretKey: TELEMETRY_HMAC_KEY
      remoteRef:
        key: k8s/honeypot-rs/runtime/TELEMETRY_HMAC_KEY
    - secretKey: LURE_HMAC_KEY
      remoteRef:
        key: k8s/honeypot-rs/runtime/LURE_HMAC_KEY
